### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [gonzalobellino/buidler-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by gonzalobellino** [comment]
Thank you @unixorn for your recommendation. I will do it shortly

**Comment by gonzalobellino** [comment]
Licence added  (https://github.com/gonzalobellino/buidler-zsh/releases/tag/0.1.0)
